/*
 *    Copyright (C) 2013, Jules Colding <jcolding@gmail.com>.
 *
 *    All Rights Reserved.
 */

/*
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 *
 *     (1) Redistributions of source code must retain the above
 *     copyright notice, this list of conditions and the following
 *     disclaimer.
 *
 *     (2) Redistributions in binary form must reproduce the above
 *     copyright notice, this list of conditions and the following
 *     disclaimer in the documentation and/or other materials provided
 *     with the distribution.
 *
 *     (3) Neither the name of the copyright holder nor the names of
 *     its contributors may be used to endorse or promote products
 *     derived from this software without specific prior written
 *     permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE AUTHOR ``AS IS'' AND ANY EXPRESS
 * OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
 * WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
 * ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR
 * CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
 * SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
 * LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF
 * USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
 * ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
 * OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT
 * OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
 * SUCH DAMAGE.
 */

#include "fix_types.h"

#ifdef HAVE_CONFIG_H
    #include "ac_config.h"
#endif

const struct FIX_Tag fix42_std_tags[] =
{
        {1, ft_String},
        {2, ft_String},
        {3, ft_String},
        {4, ft_char},
        {5, ft_String},
        {6, ft_Price},
        {7, ft_int},
        {8, ft_String},
        {9, ft_int},
        {10, ft_String},
        {11, ft_String},
        {12, ft_Amt},
        {13, ft_char},
        {14, ft_Qty},
        {15, ft_Currency},
        {16, ft_int},
        {17, ft_String},
        {18, ft_MultipleCharValue},
        {19, ft_String},
        {20, ft_char},
        {21, ft_char},
        {22, ft_String},
        {23, ft_String},
        {24, ft_char},
        {25, ft_char},
        {26, ft_String},
        {27, ft_String},
        {28, ft_char},
        {29, ft_char},
        {30, ft_Exchange},
        {31, ft_Price},
        {32, ft_Qty},
        {33, ft_int},
        {34, ft_int},
        {35, ft_String},
        {36, ft_int},
        {37, ft_String},
        {38, ft_Qty},
        {39, ft_char},
        {40, ft_char},
        {41, ft_String},
        {42, ft_UTCTimestamp},
        {43, ft_Boolean},
        {44, ft_Price},
        {45, ft_int},
        {46, ft_String},
        {47, ft_char},
        {48, ft_String},
        {49, ft_String},
        {50, ft_String},
        {51, ft_LocalMktDate},
        {52, ft_UTCTimestamp},
        {53, ft_Qty},
        {54, ft_char},
        {55, ft_String},
        {56, ft_String},
        {57, ft_String},
        {58, ft_String},
        {59, ft_char},
        {60, ft_UTCTimestamp},
        {61, ft_char},
        {62, ft_UTCTimestamp},
        {63, ft_char},
        {64, ft_LocalMktDate},
        {65, ft_String},
        {66, ft_String},
        {67, ft_int},
        {68, ft_int},
        {69, ft_String},
        {70, ft_String},
        {71, ft_char},
        {72, ft_String},
        {73, ft_int},
        {74, ft_int},
        {75, ft_LocalMktDate},
        {76, ft_String},
        {77, ft_char},
        {78, ft_int},
        {79, ft_String},
        {80, ft_Qty},
        {81, ft_char},
        {82, ft_int},
        {83, ft_int},
        {84, ft_Qty},
        {85, ft_int},
        {86, ft_String},
        {87, ft_int},
        {88, ft_int},
        {89, ft_data},
        {90, ft_Length},
        {91, ft_data},
        {92, ft_String},
        {93, ft_Length},
        {94, ft_char},
        {95, ft_Length},
        {96, ft_data},
        {97, ft_Boolean},
        {98, ft_int},
        {99, ft_Price},
        {100, ft_Exchange},
        {102, ft_int},
        {103, ft_int},
        {104, ft_char},
        {105, ft_String},
        {106, ft_String},
        {107, ft_String},
        {108, ft_int},
        {109, ft_String},
        {110, ft_Qty},
        {111, ft_Qty},
        {112, ft_String},
        {113, ft_Boolean},
        {114, ft_Boolean},
        {115, ft_String},
        {116, ft_String},
        {117, ft_String},
        {118, ft_Amt},
        {119, ft_Amt},
        {120, ft_Currency},
        {121, ft_Boolean},
        {122, ft_UTCTimestamp},
        {123, ft_Boolean},
        {124, ft_int},
        {125, ft_char},
        {126, ft_UTCTimestamp},
        {127, ft_char},
        {128, ft_String},
        {129, ft_String},
        {130, ft_Boolean},
        {131, ft_String},
        {132, ft_Price},
        {133, ft_Price},
        {134, ft_Qty},
        {135, ft_Qty},
        {136, ft_int},
        {137, ft_Amt},
        {138, ft_Currency},
        {139, ft_char},
        {140, ft_Price},
        {141, ft_Boolean},
        {142, ft_String},
        {143, ft_String},
        {144, ft_String},
        {145, ft_String},
        {146, ft_int},
        {147, ft_String},
        {148, ft_String},
        {149, ft_String},
        {150, ft_char},
        {151, ft_Qty},
        {152, ft_Qty},
        {153, ft_Price},
        {154, ft_Amt},
        {155, ft_float},
        {156, ft_char},
        {157, ft_int},
        {158, ft_float},
        {159, ft_Amt},
        {160, ft_char},
        {161, ft_String},
        {162, ft_String},
        {163, ft_char},
        {164, ft_String},
        {165, ft_char},
        {166, ft_String},
        {167, ft_String},
        {168, ft_UTCTimestamp},
        {169, ft_int},
        {170, ft_String},
        {171, ft_String},
        {172, ft_int},
        {173, ft_String},
        {174, ft_String},
        {175, ft_String},
        {176, ft_String},
        {177, ft_String},
        {178, ft_String},
        {179, ft_String},
        {180, ft_String},
        {181, ft_String},
        {182, ft_String},
        {183, ft_String},
        {184, ft_String},
        {185, ft_String},
        {186, ft_String},
        {187, ft_String},
        {188, ft_Price},
        {189, ft_Price},
        {190, ft_Price},
        {191, ft_Price},
        {192, ft_Qty},
        {193, ft_LocalMktDate},
        {194, ft_Price},
        {195, ft_Price},
        {196, ft_String},
        {197, ft_int},
        {198, ft_String},
        {199, ft_int},
        {200, ft_MonthYear},
        {201, ft_int},
        {202, ft_Price},
        {203, ft_int},
        {204, ft_int},
        {205, ft_DayOfMonth},
        {206, ft_char},
        {207, ft_Exchange},
        {208, ft_Boolean},
        {209, ft_int},
        {210, ft_Qty},
        {211, ft_Price},
        {212, ft_Length},
        {213, ft_data},
        {214, ft_String},
        {215, ft_int},
        {216, ft_int},
        {217, ft_String},
        {218, ft_Price},
        {219, ft_char},
        {223, ft_float},
        {231, ft_float},
        {262, ft_String},
        {263, ft_char},
        {264, ft_int},
        {265, ft_int},
        {266, ft_Boolean},
        {267, ft_int},
        {268, ft_int},
        {269, ft_char},
        {270, ft_Price},
        {271, ft_Qty},
        {272, ft_UTCDateOnly},
        {273, ft_UTCTimeOnly},
        {274, ft_char},
        {275, ft_Exchange},
        {276, ft_MultipleStringValue},
        {277, ft_MultipleStringValue},
        {278, ft_String},
        {279, ft_char},
        {280, ft_String},
        {281, ft_char},
        {282, ft_String},
        {283, ft_String},
        {284, ft_String},
        {285, ft_char},
        {286, ft_char},
        {287, ft_int},
        {288, ft_String},
        {289, ft_String},
        {290, ft_int},
        {291, ft_char},
        {292, ft_char},
        {293, ft_Qty},
        {294, ft_Qty},
        {295, ft_int},
        {296, ft_int},
        {297, ft_int},
        {298, ft_int},
        {299, ft_String},
        {300, ft_int},
        {301, ft_int},
        {302, ft_String},
        {303, ft_int},
        {304, ft_int},
        {305, ft_String},
        {306, ft_String},
        {307, ft_String},
        {308, ft_Exchange},
        {309, ft_String},
        {310, ft_String},
        {311, ft_String},
        {312, ft_String},
        {313, ft_MonthYear},
        {314, ft_DayOfMonth},
        {315, ft_int},
        {316, ft_Price},
        {317, ft_char},
        {318, ft_Currency},
        {319, ft_Qty},
        {320, ft_String},
        {321, ft_int},
        {322, ft_String},
        {323, ft_int},
        {324, ft_String},
        {325, ft_Boolean},
        {326, ft_int},
        {327, ft_char},
        {328, ft_Boolean},
        {329, ft_Boolean},
        {330, ft_Qty},
        {331, ft_Qty},
        {332, ft_Price},
        {333, ft_Price},
        {334, ft_int},
        {335, ft_String},
        {336, ft_String},
        {337, ft_String},
        {338, ft_int},
        {339, ft_int},
        {340, ft_int},
        {341, ft_UTCTimestamp},
        {342, ft_UTCTimestamp},
        {343, ft_UTCTimestamp},
        {344, ft_UTCTimestamp},
        {345, ft_UTCTimestamp},
        {346, ft_int},
        {347, ft_String},
        {348, ft_Length},
        {349, ft_data},
        {350, ft_Length},
        {351, ft_data},
        {352, ft_Length},
        {353, ft_data},
        {354, ft_Length},
        {355, ft_data},
        {356, ft_Length},
        {357, ft_data},
        {358, ft_Length},
        {359, ft_data},
        {360, ft_Length},
        {361, ft_data},
        {362, ft_Length},
        {363, ft_data},
        {364, ft_Length},
        {365, ft_data},
        {366, ft_Price},
        {367, ft_UTCTimestamp},
        {368, ft_int},
        {369, ft_int},
        {370, ft_UTCTimestamp},
        {371, ft_int},
        {372, ft_String},
        {373, ft_int},
        {374, ft_char},
        {375, ft_String},
        {376, ft_String},
        {377, ft_Boolean},
        {378, ft_int},
        {379, ft_String},
        {380, ft_int},
        {381, ft_Amt},
        {382, ft_int},
        {383, ft_int},
        {384, ft_int},
        {385, ft_char},
        {386, ft_int},
        {387, ft_Qty},
        {388, ft_char},
        {389, ft_Price},
        {390, ft_String},
        {391, ft_String},
        {392, ft_String},
        {393, ft_int},
        {394, ft_int},
        {395, ft_int},
        {396, ft_Amt},
        {397, ft_Amt},
        {398, ft_int},
        {399, ft_int},
        {400, ft_String},
        {401, ft_int},
        {402, ft_float},
        {403, ft_float},
        {404, ft_Amt},
        {405, ft_float},
        {406, ft_Amt},
        {407, ft_float},
        {408, ft_Amt},
        {409, ft_int},
        {410, ft_float},
        {411, ft_Boolean},
        {412, ft_Amt},
        {413, ft_float},
        {414, ft_int},
        {415, ft_int},
        {416, ft_int},
        {417, ft_int},
        {418, ft_char},
        {419, ft_char},
        {420, ft_int},
        {421, ft_String},
        {422, ft_int},
        {423, ft_int},
        {424, ft_Qty},
        {425, ft_Qty},
        {426, ft_Price},
        {427, ft_int},
        {428, ft_int},
        {429, ft_int},
        {430, ft_int},
        {431, ft_int},
        {432, ft_LocalMktDate},
        {433, ft_char},
        {434, ft_char},
        {435, ft_float},
        {436, ft_float},
        {437, ft_Qty},
        {438, ft_UTCTimestamp},
        {439, ft_String},
        {440, ft_String},
        {441, ft_int},
        {442, ft_char},
        {443, ft_UTCTimestamp},
        {444, ft_String},
        {445, ft_Length},
        {446, ft_data},
        {0, ft_int}, // terminating 0 tag
};

const struct FIX_Tag fix42_std_data_tags[] =
{
        {89, ft_data},
        {91, ft_data},
        {96, ft_data},
        {213, ft_data},
        {349, ft_data},
        {351, ft_data},
        {353, ft_data},
        {355, ft_data},
        {357, ft_data},
        {359, ft_data},
        {361, ft_data},
        {363, ft_data},
        {365, ft_data},
        {446, ft_data},
        {0, ft_int}, // terminating 0 tag
};
